# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [ commit, push ]
repos:
  # pre-commit formatting hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Replace by any tag/version:
    hooks:
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-added-large-files
        args: [ '--maxkb=128' ]
      - id: mixed-line-ending
      - id: fix-encoding-pragma
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      # - id: no-commit-to-branch # personal project - just do main directly for now
      - id: fix-encoding-pragma
      - id: name-tests-test
        args: [ "--pytest-test-first" ]
      - id: check-builtin-literals
      - id: check-ast
  # ensure notebook is clean before committed
  - repo: https://github.com/mudiarto/nbhooks.git
    rev: 1.5.0  # Use `pre-commit autoupdate --bleeding-edge` to set to most recent version
    hooks:
    - id: nb-ensure-clean
      args: [--meta, "editable|slideshow|tags", --fix] # keep output, errored out instead of auto clean
  # clean and simplify jupyter notebook
  - repo: https://github.com/fastai/nbdev
    rev: 2.3.13
    hooks:
      - id: nbdev_clean
      # - id: nbdev_export  # I got error - will try again in the future
  # gitleaks secret scanning
  # - repo: https://github.com/zricethezav/gitleaks
  #   rev: v8.18.2  # Replace by any tag/version: https://github.com/zricethezav/gitleaks/releases
  #   hooks:
  #     - id: gitleaks-docker
  # ruff formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
