name: ml-notebooks
#
# WARNING: keep it sync with environment.yml - except for cuda related packages
#
# This is the most straightforward way to keep the environment file in sync - since environment.yml (AFAIK) doesn't
# support conditional import, or import from 2 environment files
# If I call conda install twice, it may caus dependency calculation issues (e.g. some packages got downgraded on the
# 2nd call)
#
channels:
  - nvidia
  - pytorch
  - fastai
  - conda-forge
  - nodefaults
dependencies:
  - nodejs
  - python=3.11
  - pre-commit
  # ML & AI library
  - pytorch
  - torchvision
  - torchaudio
  - fastai
  - scikit-learn
  #
  # cuda library - please comment in environment.yml
  #
  - pytorch-cuda
  - cuda
  - cudatoolkit
  #
  # ml ui
  - gradio
  - ipywidgets
  # jupyterlab & development
  - jupyterlab
  - voila
  - nbdev
  - jupyterlab_vim
    # jupyter-ai & its dependencies (langchain-openai)
  - jupyter-ai
  - jupyter-ai-magics
  - langchain-openai
  # seems required by nbdev
  - fsspec
  # jupyter alternative
  - marimo
  # graphic
  - matplotlib
  - seaborn
  - plotly
  - altair-all
  - Pillow
  # debugging
  - icecream
  # pip
  - pip
  - pip:
    - -r requirements.txt
