name: ml-notebooks
channels:
  - pytorch
  - conda-forge
dependencies:
  - nodejs
  - python=3.11
  - pre-commit
  - pytorch
  - marimo
  - matplotlib
  - plotly
  - pip
  - pip:
    - -r requirements.txt
