name: ml-notebooks
channels:
  - pytorch
  - nvidia
  - fastai
  - conda-forge
dependencies:
  - nodejs
  - python=3.11
  - pre-commit
  # ML & AI library
  - pytorch
  - torchvision
  - torchaudio
  - fastai
  - scikit-learn
  # cuda installed separately using conda directly - so we can use the same file on non-cuda environment
  # - pytorch-cuda
  # - cuda
  #
  # ml ui
  - gradio
  - ipywidgets
  # jupyterlab & development
  - jupyterlab
  - voila
  - nbdev
  - jupyterlab_vim
    # jupyter-ai & its dependencies (langchain-openai)
  - jupyter-ai
  - jupyter-ai-magics
  - langchain-openai
  # seems required by nbdev
  - fsspec
  # jupyter alternative
  - marimo
  # graphic
  - matplotlib
  - seaborn
  - plotly
  - altair-all
  - Pillow
  # debugging
  - icecream
  # pip
  - pip
  - pip:
    - -r requirements.txt
